language: node_js
node_js:
  - "8"
  - "10"
  - "12"

cache: npm

install:
  - npm install --save-dev

script:
  - npm run test

jobs:
  include:
    - stage: build
      node_js: 10
      script: npm run build
    - stage: release
      node_js: lts/*
      deploy:
        on:
          branch: master
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
