language: node_js

node_js:
  - "10"
  - "12"

os:
  - windows
  - linux

matrix:
  allow_failures:
    - os: windows

cache: npm

install:
  - npm install --save-dev

script:
  - npm run test

branches:
  except:
  - /^legacy\/.*$/
  - /^experimental\/.*$/
  - assets
  - gh-pages

jobs:
  include:
    - stage: build
      node_js: 12
      script: npm run build
    - stage: release
      node_js: lts/*
      deploy:
        on:
          branch: master
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
    - stage: release-candidate
      node_js: lts/*
      deploy:
        on:
          branch: next
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
