language: node_js
node_js:
  - "8"
  - "10"
  - "12"
cache: npm
install:
  - npm install --save-dev
script:
  - npm run test
  - npm run build
jobs:
  include:
    - stage: release
      node_js: lts/*
